* Non-maintainer upload. * Fix FTBFS due to undefined reference to `pango_x_render', thanks to Emilio Pozuelo Monfort <pochu@debian.org> for the patch. Closes: #701837, #713619
-- David Prevot <taffit@debian.org>  Sat, 06 Jul 2013 22:31:15 -0400